### PR TITLE
dataset['title'] is a required field

### PR DESCRIPTION
**Pull request by Bento007**

### CODE REVIEW

**Review by bkmartinjr — APPROVED** [review]
Optional: If you have time, this might be a good time to add a validator for the `datasets` DataFrame in the `census_info` collection.  Minimally just confirm that for all datasets, the required fields are present.

**Comment by atolopko-czi** [comment]
> Optional: If you have time, this might be a good time to add a validator for the `datasets` DataFrame in the `census_info` collection. Minimally just confirm that for all datasets, the required fields are present.

💯.  Note that this validation could be taken on as part of https://github.com/chanzuckerberg/cell-census/issues/111 which asks that all dataset metadata attributes are validated.

**Review by atolopko-czi — APPROVED** [review]
LGTM

**Comment by Bento007** [comment]
Since this is already approve I will add this to a future PR

**Pull request merged**
